### ISSUE TITLE
Unable to query .co.uk domain due to wrong created_date

### ISSUE THREAD

**Issue by mydigia** [turbot/steampipe-plugin-whois#15]
When querying a .co.uk domain, I get:

`interfaceToColumnValue failed for column 'created_date': found XX, expected yyyy-mm-dd or yyyymmdd`

`steampipe version 0.7.2`

`steampipe plugin list`
+--------------------------------------------------+---------+----------------------+
| Name                                             | Version | Connections          |
+--------------------------------------------------+---------+----------------------+
| hub.steampipe.io/plugins/turbot/aws@latest       | 0.29.0  | xxxx |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 0.1.3   | steampipe            |
| hub.steampipe.io/plugins/turbot/whois@latest     | 0.1.3   | whois                |
+--------------------------------------------------+---------+----------------------+

How to reproduce: query a .co.uk domain to reproduce

Expected result: query and show results like other domains

**Comment by mydigia** [comment]
For example:
`select
  *
from
  whois_domain
where
  domain in ('domain.co.uk');`

**Comment by e-gineer** [comment]
Hey @mydigia ... thanks for using Steampipe and for reporting this issue.

I've been able to reproduce:

```
> select * from whois_domain where domain = 'tesco.co.uk'
Error: interfaceToColumnValue failed for column 'created_date': found b, expected number
```

As a workaround, you can select specific columns avoiding the date parsing failures. For example:
```
> select domain, name_servers from whois_domain where domain = 'tesco.co.uk'
+-------------+--------------------------+
| domain      | name_servers             |
+-------------+--------------------------+
| tesco.co.uk | ["pdns194.ultradns.biz"] |
+-------------+--------------------------+
```

Turns out the UK WHOIS returns some pretty interesting date formats! We'll need to work out how to degrade nicely...
```
> select domain, raw->'domain'->>'created_date' as created_date from whois_domain where domain in ('stripe.co.uk', 'tesco.co.uk');
+--------------+-----------------+
| domain       | created_date    |
+--------------+-----------------+
| stripe.co.uk | 14-Jul-2011     |
| tesco.co.uk  | before Aug-1996 |
+--------------+-----------------+
```

**Comment by e-gineer** [comment]
Fix above makes things more forgiving / reliable:
```
> select domain, created_date, expiration_date from whois_domain where domain in ('stripe.co.uk', 'tesco.co.uk', 'steampipe.io');
+--------------+---------------------+---------------------+
| domain       | created_date        | expiration_date     |
+--------------+---------------------+---------------------+
| tesco.co.uk  | <null>              | 2022-01-30 00:00:00 |
| stripe.co.uk | 2011-07-14 00:00:00 | 2023-07-14 00:00:00 |
| steampipe.io | 2020-10-13 19:28:29 | 2021-10-13 19:28:29 |
+--------------+---------------------+---------------------+
```

I've decided to live with the fact that `before Aug-1996` returns `null` for now. I don't think it's hugely critical, `null` indicates that we don't know, and there will be a largely infinite set of formats if we go down that route.

Thanks again @mydigia for the feedback!
