### ISSUE TITLE
Whois deprecation - migrate to RDAP

### ISSUE THREAD

**Issue by lyda** [turbot/steampipe-plugin-whois#35]
The whois "protocol" is [being deprecated](https://domainincite.com/28761-icann-signs-whois-death-warrant-in-new-contracts) in favour of [RDAP](https://www.rfc-editor.org/rfc/rfc7482). Would there be interest in looking to adding RDAP functionality to this repo?

The migration seems like it will take a few years since it's based on registrar contract renewals. And a number of registrars have said they'll end whois services after a period of operating both - but again this will be on a rolling schedule. So the solution seems to be to try both to answer queries - specifically try RDAP and if it fails, try whois.

Alternatively there could be an rdap specific plugin. The issue is the overlap period where for some registrars will only support whois, some will support both and some will only support rdap. There's an argument that the name is confusing, but I suspect the term "whois" will refer to the data regardless of the protocol.

There's an existing Go [RDAP library](https://pkg.go.dev/github.com/openrdap/rdap) that should make it relatively easy to do.

**Comment by cbruno10** [comment]
@lyda Thanks for raising this issue and PR!

It feels like RDAP is separate enough to be its own plugin, based on naming for searchability, under, etc. If a domain doesn't support RDAP yet, the WHOIS plugin will still be available for use.

@johnsmyth - Any thoughts on a separate plugin vs. a separate table in this repo, e.g., `rdap_domain`?

**Comment by johnsmyth** [comment]
Im not very familiar with the details - how compatible are the responses?  Depending on how much they vary, it might not really be useful to capture them in a single table anyway?

**Comment by lyda** [comment]
Oh, and if it helps, these are the corresponding Go types:

  * `rdap.Domain`: https://pkg.go.dev/github.com/openrdap/rdap#Domain
  * `whoisparser.WhoisInfo`: https://pkg.go.dev/github.com/likexian/whois-parser#WhoisInfo

As an aside, I suspect people will pronounce RDAP "whois" for a long time. Just like the save icon is still a 3.5" floppy disk and we still talk about "albums" with relation to music. In terms of language, I think the name of this plugin long after nothing listens to port 43.

**Comment by misraved** [comment]
@lyda @cbruno10 IMO, a new plugin would be a better solution considering we have all means to access the APIs. In future after the deprecation comes through, it would become difficult to rename/deprecate this plugin and create a new one for RDAP.

**Comment by johnsmyth** [comment]
I think I agree with @lyda that folks will continue to refer to it as **whois** even when it is technically RDAP, so i dont mind adding support for RDAP in this plugin.  We do something similar for RSS - the RSS plugin supports both RSS and Atom.

**Comment by cbruno10** [comment]
@lyda @johnsmyth That's a good point, in the future if we ever want to have an RDAP plugin, we could create it then and deprecate the table in this plugin (if required).

@lyda Please let us know when https://github.com/turbot/steampipe-plugin-whois/pull/36 is ready for review (or if it already is) and we'll have a pass at it, thanks!

**Comment by lyda** [comment]
Little busy this week but will get to it again Saturday morning Irish time. I think the PR is mostly there but would like to review it and add comments on my decisions.

Also need to see if there are columns we could get from rdap that are missing from that WhoisInfo (sp?) type. At the very least I can document them.

**Comment by cbruno10** [comment]
Thanks @lyda , no rush of course! Looking forward to adding RDAP support soon 😃

**Comment by lyda** [comment]
OK, looked through it and the PR is ready. I have some thoughts. Might want to add a few columns - maybe an rdap_server and some of the rdap fields.
